### ISSUE TITLE
Vectorized FindPeriodLFP

### ISSUE THREAD

**Issue by elsahh** [neuromotion/PARRM#1]
Hello,

Thanks for your work! I am hoping to use this on a stimulation project I am working on. I have several channels recorded simultaneously from which I would like to extract the stimulation artifact. For this, I have tried using a for loop, but it is taking painfully long. Is there any way to vectorize my call to FindPeriodLFP.m, such that all channels are treated simultaneously? 

In short, is there any way to pass a matrix (nchannels x nsamples), rather than a 1xnsamples vector, to FindPeriodLFP.m? 

Thanks!

**Comment by theonlydvr** [comment]
Hello!

If you have many channels in parallel, you should only have to call FindPeriodLFP on a single channel since the artifact period should be identical across all recorded channels. Typically, I would use the channel with the strongest artifact to find the period for the PARRM filter. The filter itself should then be easily amenable for vectorized processing.

Let me know if you have any further questions!

**Comment by elsahh** [comment]
That makes a lot of sense, thank you!

**Comment by elsahh** [comment]
That makes a lot of sense, thank you!
